### ISSUE TITLE
Kubuntu support

### ISSUE THREAD

**Issue by vkosachev** [ziyenano/Guake-Color-Schemes#4]
Hey, nice work you have done. 
Cannot get this working as on the gif you've provided on kubuntu 17.04. 
Can you guide me what is possible to adjust to have this working ?

**Comment by ziyenano** [comment]
@vkosachev 
I have not tried a kubuntu OS, but I guess it should work on that platform.
Ensure that you run the script in guake terminal;
Run "./guake_theme.sh  theme_name" to test whether the basic script works.
Finally,  the new guake terminal seems to have added some cool built-in themes, you can also pick one in its preference.

**Comment by vkosachev** [comment]
@ziyenano 
Actually the script works, but applies only background and text color for part of the themes.
I tried to apply the elementary scheme but got only white text on black background. 
No errors were fired but I think something is missing.

**Comment by ziyenano** [comment]
@vkosachev 
This tool mainly uses gconftool-2 function to change the two xml files in the following folders ~/.gconf/apps/guake/style/background/ and
~/.gconf/apps/guake/style/font/.  See the details in the last part of the  guake_theme.sh script.
 Checking the above xml files,  maybe you can find what cause the exception, good luck!

**Comment by lucastabelini** [comment]
Same problem here, on Elementary Loki. The script only sets the background and text color, not like in the gif that different parts of the text use different colors.

Edit:
Found the issue. On ~/.bashrc I had to change this line:
`#force_color_prompt=yes`
Just removed the comment(#) and now all the colors work fine.
