### ISSUE TITLE
Upstream to guake

### ISSUE THREAD

**Issue by gsemet** [ziyenano/Guake-Color-Schemes#5]
Hello
I am the maintainer of Guake, and I think your theme can be upstreamed to the guake palette (`palette.py`) pretty easily. I'll be happy to integrate them an make them available to all users by default :)

**Comment by ziyenano** [comment]
Of course you can and it's my pleasure.

**Comment by gsemet** [comment]
Not sure I’ll have time to do it, can you look at it ? I just came across this project and see it should not be anymore compatible with guake since the switch to dconf

**Comment by ziyenano** [comment]
Since leaving ubuntu os for a long time,  I am unaware of the compatibility with the latest guake now. If necessary, I'll put these themes into the script palette.py.

**Comment by roachsinai** [comment]
How is everything going？Expected!!!

**Comment by ziyenano** [comment]
@gsemet Sorry for the delay, I just create a new  request.
Btw, does the order of colors in my file strictly match that in palettes.py?
```
COLOR_01="#363636"          # HOST
COLOR_02="#ff0883"          # SYNTAX_STRING
COLOR_03="#83ff08"          # COMMAND
COLOR_04="#ff8308"          # COMMAND_COLOR2
COLOR_05="#0883ff"          # PATH
COLOR_06="#8308ff"          # SYNTAX_VAR
COLOR_07="#08ff83"          # PROMP
COLOR_08="#b6b6b6"          #

COLOR_09="#424242"          #
COLOR_10="#ff1e8e"          # COMMAND_ERROR
COLOR_11="#8eff1e"          # EXEC
COLOR_12="#ff8e1e"          #
COLOR_13="#1e8eff"          # FOLDER
COLOR_14="#8e1eff"          #
COLOR_15="#1eff8e"          #
COLOR_16="#c2c2c2"          #

BACKGROUND_COLOR="#0d1926"  # Background Color
FOREGROUND_COLOR="#b4e1fd"  # Text
```

**Comment by gsemet** [comment]
thanks a lot !
